In [1]:
import numpy as np

### arange

In [2]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [3]:
type(list(range(30)))

list

In [5]:
# range: List의 range와 같은 효과
# integer로 0부터 29까지 배열추출
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [7]:
np.arange(0, 5, 0.5)    # floating point도 표시가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [8]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### ones, zeros & empty

In [10]:
# 10 - zero vector 생성
np.zeros(shape=(10), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [11]:
np.zeros((2, 5))    # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [13]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.empty(shape=(10,), dtype=np.int8)

array([-112,  -66,  -81, -111,  -47,    1,    0,    0,    0,    0],
      dtype=int8)

In [15]:
np.empty((10, 5))

array([[9.87937303e-312, 9.87936984e-312, 6.40695298e+029,
        2.24706544e-310, 9.87936984e-312],
       [2.99575402e-307, 9.87937239e-312, 9.87937549e-312,
        6.57934032e-087, 1.17132761e-085],
       [2.02671556e+267, 1.21906099e-152, 5.27110623e+180,
        4.24115827e+160, 1.94487254e+227],
       [9.44633808e+218, 6.50596358e+029, 1.06400250e+248,
        6.01347002e-154, 1.27368762e+232],
       [8.77581978e-095, 1.25541827e+232, 3.69113190e+193,
        2.99027014e+267, 6.64407753e+246],
       [1.82267771e+171, 7.14265639e+247, 8.74369672e+140,
        4.24203466e+175, 2.98018707e+262],
       [6.31110884e+233, 1.15823920e-152, 9.08367206e+223,
        6.01347002e-154, 3.92573072e-027],
       [2.61625519e+209, 3.59850298e+227, 2.67978223e-080,
        1.58897871e-258, 3.68777421e+180],
       [4.47593816e-091, 2.93573416e+222, 5.04751656e+223,
        1.25767116e-076, 1.96082954e+243],
       [1.12576172e-153, 3.77471631e-096, 6.12673757e-062,
        6.19833586e-092

In [16]:
test_matrix = np.arange(100).reshape(5, -1)
test_matrix.shape

(5, 20)

In [17]:
test_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [26]:
np.zeros_like(test_matrix, dtype=np.float32)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

### eye, identity & digonal

In [28]:
np.identity(n=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [29]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
np.diag(matrix, k=-1)

array([3, 7])

In [34]:
np.diag(matrix, k=1)

array([1, 5])

### numpy.random

In [35]:
np.random.normal(0, 1, 10).reshape(2, 5)

array([[ 1.23606681, -0.74553251, -1.91917995, -1.51121941,  0.42753133],
       [-0.51636972,  0.13003833,  0.76674351,  1.28908282,  0.16677522]])

In [36]:
np.random.exponential(scale=2, size=100)

array([ 1.42126895,  3.02217776,  6.40950519,  2.31046514,  0.35227791,
        2.07008195,  2.09768477,  4.67427981,  2.6497173 ,  0.25213762,
        2.54745101,  0.23365747,  2.29744356,  0.92027268,  0.73359116,
        5.21956615,  6.59012195,  0.11143724,  1.94410084,  5.44962463,
        0.0295353 ,  3.90192854,  0.25754713,  2.67597995, 11.72693817,
        0.2896457 ,  2.47351707,  0.55177454,  5.48797249,  0.16068741,
        1.0467967 ,  3.30783611,  3.05857409,  1.10458859,  0.06996187,
        0.49468962,  2.42226686,  0.86763798,  1.14954014,  1.43760754,
        1.54171053,  2.92748291,  2.68819384,  0.68427391,  0.31056662,
        0.49051346, 10.01948276,  0.62652933,  0.59171286,  2.53482919,
        1.69269114,  6.5981    ,  2.21309235,  0.8627319 ,  9.93936946,
        3.54605289,  1.48490704,  6.10669354,  1.03437797,  0.01531364,
        5.75482471,  0.03419346,  1.00122266,  1.2102822 ,  2.05071885,
        0.68901128,  2.42637236,  0.08824436,  1.53012267,  6.22