In [1]:
import numpy as np

### boolean index

In [2]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [3]:
test_array.shape

(8,)

In [4]:
(test_array > 3).shape

(8,)

In [5]:
test_array[test_array > 3]    # 조건이 True인 index의 element만 추출

array([4., 8., 9., 7.])

In [6]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

### fancy index

In [7]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)    # 반드시 integer로 선언
a[b]    # bracket index, b배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

In [8]:
a.take(b)    # take 함수: bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [9]:
a[a > 4]

array([6., 8.])

In [10]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)

In [11]:
a[b, c]    # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

In [12]:
a = np.array([[1, 4], [9, 16]], float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])