In [1]:
import numpy as np

### all & any

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [4]:
a < 1

array([ True, False, False, False, False, False, False, False, False,
       False])

In [5]:
a <10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [6]:
np.all(a<10)

True

In [7]:
a < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [8]:
np.all(a<5)

False

### comparision operation

In [9]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)

In [10]:
test_a > test_b

array([False,  True, False])

In [11]:
test_a >= test_b

array([False,  True, False])

In [13]:
(test_a > test_b).any()

True

In [14]:
(test_a > test_b).all()

False

In [15]:
np.logical_and(a>0, a<3)

array([False,  True,  True, False, False, False, False, False, False,
       False])

In [16]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [17]:
c = np.array([False, True, False], bool)
c

array([False,  True, False])

In [18]:
np.logical_or(b, c)    # OR 조건의 condition

array([ True,  True,  True])

### np.where

In [19]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.where(a>2)

(array([3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [21]:
np.where(a < 3)[0]

array([0, 1, 2], dtype=int64)

In [22]:
np.where(a<3, 3, 2)

array([3, 3, 3, 2, 2, 2, 2, 2, 2, 2])

In [23]:
a = np.arange(5, 15)

In [24]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

In [26]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [27]:
np.isfinite(a)

array([ True, False, False])

### argmax & argmin

In [28]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [29]:
a.argsort()

array([0, 1, 7, 2, 3, 4, 6, 5], dtype=int64)

In [30]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0], dtype=int64)

In [31]:
np.argmax(a)

5

In [32]:
np.argmin(a)

0

In [33]:
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [34]:
np.argmax(a, axis=1)

array([3, 1, 1], dtype=int64)

In [35]:
np.argmin(a, axis=0)

array([0, 0, 2, 2], dtype=int64)