In [1]:
import numpy as np

### reshape

In [2]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [4]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [6]:
test_matrix    # 기존의 test_matrix는 변함 X. (할당되지 않았기 때문)

[[1, 2, 3, 4], [1, 2, 5, 8]]

In [8]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [10]:
np.array(test_matrix).reshape(2, 4)
# np.array(test_matrix).reshape(2, 4).shape

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [12]:
np.array(test_matrix).reshape(1, -1).shape

(1, 8)

In [13]:
np.array(test_matrix).reshape(1, -1, 2)

array([[[1, 2],
        [3, 4],
        [1, 2],
        [5, 8]]])

In [15]:
np.array(test_matrix).reshape(1, -1, 2).shape

(1, 4, 2)

### flat or flatten()

In [16]:
test_matrix = [[[1, 2, 3, 4], [1, 2, 5, 8]], [[1, 2, 3, 4], [1, 2, 5, 8]]]
np.array(test_matrix)

array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])

In [18]:
test_matrix = np.array(test_matrix)
test_matrix.shape

(2, 2, 4)

In [19]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [20]:
np.array(test_matrix).flatten().size

16