In [2]:
import numpy as np

### Array operations

In [3]:
test_a = np.array([[1, 2, 3], [4, 5, 6]], float)

In [4]:
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
test_a + test_a    # Matrix + Matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [6]:
test_a - test_a    # Matrix - Matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
test_a * test_a    # Matrix 내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
matrix_a = np.arange(1, 13).reshape(3, 4)
matrix_a - matrix_a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### dot product

In [12]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)

In [13]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [14]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [16]:
test_a = np.arange(1, 7).reshape(2, 3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Broadcasting

In [20]:
test_matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
scalar =3

In [21]:
test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [23]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [24]:
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [25]:
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [26]:
test_matrix //2

array([[0., 1., 1.],
       [2., 2., 3.]])

In [27]:
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [28]:
test_matrix = np.arange(1, 13).reshape(4, 3)
test_vector = np.arange(10, 40, 10)

In [29]:
test_vector

array([10, 20, 30])

In [31]:
test_vector.reshape(-1, 3).T + test_vector

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

In [30]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

### Numpy performance

In [1]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

In [ ]:
%timeit scalar_vector_product(scalar, vector)    # for loop 를 이용한 성능

In [ ]:
%timeit [scalar * vector for value in range(iternation_max)]    # list comprehension 을 이용한 성능

In [ ]:
%timeit np.arange(iternation_max) * scalar    # numpy를 이용한 성능